# Generated by Django 4.2 on 2023-04-25 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="member", name="id",),
        migrations.AddField(
            model_name="member",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="pics/"),
        ),
        migrations.AlterField(
            model_name="member",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
